### ISSUE TITLE
Garage / Gate support

### ISSUE THREAD

**Issue by Sungray** [raintonr/ioBroker.google-smart-home-fulfillment#11]
I'd love to see support for the Garage / Gate objects. As discussed, they can be ignored from the fulfillment settings, so security should be OK.

**Comment by Sungray** [comment]
Must be something weird going on, but when I try installing/updating nothing happens. Btw I can install other adapters without issue.
This also happened the first time I installed the adapter, but I savagely restarted the iobroker container and the adapter was correctly installed.

![image](https://user-images.githubusercontent.com/3531871/172464660-b7821e1f-11f9-42fa-99f2-c3150f60f023.png)

Stays like this forever:
![image](https://user-images.githubusercontent.com/3531871/172464715-1168d944-7efa-4794-9130-10de72bb2551.png)

**Comment by raintonr** [comment]
Might be because I didn't bump the version yet (I don't know what checks IoB has in place)? Try remove/reinstall or do it manually from the command line using npm?

**Comment by Sungray** [comment]
No, it's related to the npm version just had to wait 10 mins, apparently that's normal. Seems to work perfectly!

**Comment by Sungray** [comment]
Thanks a lot for being so helpful and offering this plus all the help with Loxone, it's greatly appreciated.
